{
    "namespace": "org.vortxyz.kafka.pedido.avro.model",
    "type": "record",
    "name": "PagamentoResponseAvroModel",
    "fields": [
        {
            "name": "id",
            "type": {
                "type": "string",
                "logicalType": "uuid"
            }
        },
        {
            "name": "sagaId",
            "type": {
                "type": "string",
                "logicalType": "uuid"
            }
        },
        {
            "name": "pagamentoId",
            "type": {
                "type": "string",
                "logicalType": "uuid"
            }
        },
        {
            "name": "clienteId",
            "type": {
                "type": "string",
                "logicalType": "uuid"
            }
        },
        {
            "name": "pedidoId",
            "type": {
                "type": "string",
                "logicalType": "uuid"
            }
        },
        {
            "name": "preco",
            "type": {
                "type": "bytes",
                "logicalType": "decimal",
                "precision": 10,
                "scale": 2
            }
        },
        {
            "name": "criadoEm",
            "type": {
                "type": "long",
                "logicalType": "timestamp-millis"
            }
        },
        {
            "name": "pagamentoStatus",
            "type": {
                  "type": "enum",
                  "name": "PagamentoStatus",
                  "symbols": ["COMPLETO", "CANCELADO", "FALHO"]
               }
        },
        {
            "name": "mensagensFalha",
            "type": {
                "type": "array",
                "items":{
                  "type":"string"
               }
            }
        }
    ]
}