/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.vortxyz.kafka.pedido.avro.model;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class PagamentoResponseAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7417452733253349926L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PagamentoResponseAvroModel\",\"namespace\":\"org.vortxyz.kafka.pedido.avro.model\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"sagaId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"pagamentoId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"clienteId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"pedidoId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"preco\",\"type\":{\"type\":\"bytes\",\"logicalType\":\"decimal\",\"precision\":10,\"scale\":2}},{\"name\":\"criadoEm\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"pagamentoStatus\",\"type\":{\"type\":\"enum\",\"name\":\"PagamentoStatus\",\"symbols\":[\"COMPLETO\",\"CANCELADO\",\"FALHO\"]}},{\"name\":\"mensagensFalha\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
    MODEL$.addLogicalTypeConversion(new org.apache.avro.Conversions.DecimalConversion());
  }

  private static final BinaryMessageEncoder<PagamentoResponseAvroModel> ENCODER =
      new BinaryMessageEncoder<PagamentoResponseAvroModel>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<PagamentoResponseAvroModel> DECODER =
      new BinaryMessageDecoder<PagamentoResponseAvroModel>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<PagamentoResponseAvroModel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<PagamentoResponseAvroModel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<PagamentoResponseAvroModel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<PagamentoResponseAvroModel>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this PagamentoResponseAvroModel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a PagamentoResponseAvroModel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a PagamentoResponseAvroModel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static PagamentoResponseAvroModel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String id;
  private java.lang.String sagaId;
  private java.lang.String pagamentoId;
  private java.lang.String clienteId;
  private java.lang.String pedidoId;
  private java.math.BigDecimal preco;
  private java.time.Instant criadoEm;
  private org.vortxyz.kafka.pedido.avro.model.PagamentoStatus pagamentoStatus;
  private java.util.List<java.lang.String> mensagensFalha;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PagamentoResponseAvroModel() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param sagaId The new value for sagaId
   * @param pagamentoId The new value for pagamentoId
   * @param clienteId The new value for clienteId
   * @param pedidoId The new value for pedidoId
   * @param preco The new value for preco
   * @param criadoEm The new value for criadoEm
   * @param pagamentoStatus The new value for pagamentoStatus
   * @param mensagensFalha The new value for mensagensFalha
   */
  public PagamentoResponseAvroModel(java.lang.String id, java.lang.String sagaId, java.lang.String pagamentoId, java.lang.String clienteId, java.lang.String pedidoId, java.math.BigDecimal preco, java.time.Instant criadoEm, org.vortxyz.kafka.pedido.avro.model.PagamentoStatus pagamentoStatus, java.util.List<java.lang.String> mensagensFalha) {
    this.id = id;
    this.sagaId = sagaId;
    this.pagamentoId = pagamentoId;
    this.clienteId = clienteId;
    this.pedidoId = pedidoId;
    this.preco = preco;
    this.criadoEm = criadoEm.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
    this.pagamentoStatus = pagamentoStatus;
    this.mensagensFalha = mensagensFalha;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return sagaId;
    case 2: return pagamentoId;
    case 3: return clienteId;
    case 4: return pedidoId;
    case 5: return preco;
    case 6: return criadoEm;
    case 7: return pagamentoStatus;
    case 8: return mensagensFalha;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      null,
      null,
      new org.apache.avro.Conversions.DecimalConversion(),
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null,
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = value$ != null ? value$.toString() : null; break;
    case 1: sagaId = value$ != null ? value$.toString() : null; break;
    case 2: pagamentoId = value$ != null ? value$.toString() : null; break;
    case 3: clienteId = value$ != null ? value$.toString() : null; break;
    case 4: pedidoId = value$ != null ? value$.toString() : null; break;
    case 5: preco = (java.math.BigDecimal)value$; break;
    case 6: criadoEm = (java.time.Instant)value$; break;
    case 7: pagamentoStatus = (org.vortxyz.kafka.pedido.avro.model.PagamentoStatus)value$; break;
    case 8: mensagensFalha = (java.util.List<java.lang.String>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.String getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.String value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'sagaId' field.
   * @return The value of the 'sagaId' field.
   */
  public java.lang.String getSagaId() {
    return sagaId;
  }


  /**
   * Sets the value of the 'sagaId' field.
   * @param value the value to set.
   */
  public void setSagaId(java.lang.String value) {
    this.sagaId = value;
  }

  /**
   * Gets the value of the 'pagamentoId' field.
   * @return The value of the 'pagamentoId' field.
   */
  public java.lang.String getPagamentoId() {
    return pagamentoId;
  }


  /**
   * Sets the value of the 'pagamentoId' field.
   * @param value the value to set.
   */
  public void setPagamentoId(java.lang.String value) {
    this.pagamentoId = value;
  }

  /**
   * Gets the value of the 'clienteId' field.
   * @return The value of the 'clienteId' field.
   */
  public java.lang.String getClienteId() {
    return clienteId;
  }


  /**
   * Sets the value of the 'clienteId' field.
   * @param value the value to set.
   */
  public void setClienteId(java.lang.String value) {
    this.clienteId = value;
  }

  /**
   * Gets the value of the 'pedidoId' field.
   * @return The value of the 'pedidoId' field.
   */
  public java.lang.String getPedidoId() {
    return pedidoId;
  }


  /**
   * Sets the value of the 'pedidoId' field.
   * @param value the value to set.
   */
  public void setPedidoId(java.lang.String value) {
    this.pedidoId = value;
  }

  /**
   * Gets the value of the 'preco' field.
   * @return The value of the 'preco' field.
   */
  public java.math.BigDecimal getPreco() {
    return preco;
  }


  /**
   * Sets the value of the 'preco' field.
   * @param value the value to set.
   */
  public void setPreco(java.math.BigDecimal value) {
    this.preco = value;
  }

  /**
   * Gets the value of the 'criadoEm' field.
   * @return The value of the 'criadoEm' field.
   */
  public java.time.Instant getCriadoEm() {
    return criadoEm;
  }


  /**
   * Sets the value of the 'criadoEm' field.
   * @param value the value to set.
   */
  public void setCriadoEm(java.time.Instant value) {
    this.criadoEm = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Gets the value of the 'pagamentoStatus' field.
   * @return The value of the 'pagamentoStatus' field.
   */
  public org.vortxyz.kafka.pedido.avro.model.PagamentoStatus getPagamentoStatus() {
    return pagamentoStatus;
  }


  /**
   * Sets the value of the 'pagamentoStatus' field.
   * @param value the value to set.
   */
  public void setPagamentoStatus(org.vortxyz.kafka.pedido.avro.model.PagamentoStatus value) {
    this.pagamentoStatus = value;
  }

  /**
   * Gets the value of the 'mensagensFalha' field.
   * @return The value of the 'mensagensFalha' field.
   */
  public java.util.List<java.lang.String> getMensagensFalha() {
    return mensagensFalha;
  }


  /**
   * Sets the value of the 'mensagensFalha' field.
   * @param value the value to set.
   */
  public void setMensagensFalha(java.util.List<java.lang.String> value) {
    this.mensagensFalha = value;
  }

  /**
   * Creates a new PagamentoResponseAvroModel RecordBuilder.
   * @return A new PagamentoResponseAvroModel RecordBuilder
   */
  public static org.vortxyz.kafka.pedido.avro.model.PagamentoResponseAvroModel.Builder builder() {
    return new org.vortxyz.kafka.pedido.avro.model.PagamentoResponseAvroModel.Builder();
  }

  /**
   * Creates a new PagamentoResponseAvroModel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PagamentoResponseAvroModel RecordBuilder
   */
  public static org.vortxyz.kafka.pedido.avro.model.PagamentoResponseAvroModel.Builder builder(org.vortxyz.kafka.pedido.avro.model.PagamentoResponseAvroModel.Builder other) {
    if (other == null) {
      return new org.vortxyz.kafka.pedido.avro.model.PagamentoResponseAvroModel.Builder();
    } else {
      return new org.vortxyz.kafka.pedido.avro.model.PagamentoResponseAvroModel.Builder(other);
    }
  }

  /**
   * Creates a new PagamentoResponseAvroModel RecordBuilder by copying an existing PagamentoResponseAvroModel instance.
   * @param other The existing instance to copy.
   * @return A new PagamentoResponseAvroModel RecordBuilder
   */
  public static org.vortxyz.kafka.pedido.avro.model.PagamentoResponseAvroModel.Builder builder(org.vortxyz.kafka.pedido.avro.model.PagamentoResponseAvroModel other) {
    if (other == null) {
      return new org.vortxyz.kafka.pedido.avro.model.PagamentoResponseAvroModel.Builder();
    } else {
      return new org.vortxyz.kafka.pedido.avro.model.PagamentoResponseAvroModel.Builder(other);
    }
  }

  /**
   * RecordBuilder for PagamentoResponseAvroModel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PagamentoResponseAvroModel>
    implements org.apache.avro.data.RecordBuilder<PagamentoResponseAvroModel> {

    private java.lang.String id;
    private java.lang.String sagaId;
    private java.lang.String pagamentoId;
    private java.lang.String clienteId;
    private java.lang.String pedidoId;
    private java.math.BigDecimal preco;
    private java.time.Instant criadoEm;
    private org.vortxyz.kafka.pedido.avro.model.PagamentoStatus pagamentoStatus;
    private java.util.List<java.lang.String> mensagensFalha;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.vortxyz.kafka.pedido.avro.model.PagamentoResponseAvroModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.sagaId)) {
        this.sagaId = data().deepCopy(fields()[1].schema(), other.sagaId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.pagamentoId)) {
        this.pagamentoId = data().deepCopy(fields()[2].schema(), other.pagamentoId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.clienteId)) {
        this.clienteId = data().deepCopy(fields()[3].schema(), other.clienteId);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.pedidoId)) {
        this.pedidoId = data().deepCopy(fields()[4].schema(), other.pedidoId);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.preco)) {
        this.preco = data().deepCopy(fields()[5].schema(), other.preco);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.criadoEm)) {
        this.criadoEm = data().deepCopy(fields()[6].schema(), other.criadoEm);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.pagamentoStatus)) {
        this.pagamentoStatus = data().deepCopy(fields()[7].schema(), other.pagamentoStatus);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.mensagensFalha)) {
        this.mensagensFalha = data().deepCopy(fields()[8].schema(), other.mensagensFalha);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
    }

    /**
     * Creates a Builder by copying an existing PagamentoResponseAvroModel instance
     * @param other The existing instance to copy.
     */
    private Builder(org.vortxyz.kafka.pedido.avro.model.PagamentoResponseAvroModel other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.sagaId)) {
        this.sagaId = data().deepCopy(fields()[1].schema(), other.sagaId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.pagamentoId)) {
        this.pagamentoId = data().deepCopy(fields()[2].schema(), other.pagamentoId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.clienteId)) {
        this.clienteId = data().deepCopy(fields()[3].schema(), other.clienteId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.pedidoId)) {
        this.pedidoId = data().deepCopy(fields()[4].schema(), other.pedidoId);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.preco)) {
        this.preco = data().deepCopy(fields()[5].schema(), other.preco);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.criadoEm)) {
        this.criadoEm = data().deepCopy(fields()[6].schema(), other.criadoEm);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.pagamentoStatus)) {
        this.pagamentoStatus = data().deepCopy(fields()[7].schema(), other.pagamentoStatus);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.mensagensFalha)) {
        this.mensagensFalha = data().deepCopy(fields()[8].schema(), other.mensagensFalha);
        fieldSetFlags()[8] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.String getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public org.vortxyz.kafka.pedido.avro.model.PagamentoResponseAvroModel.Builder setId(java.lang.String value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public org.vortxyz.kafka.pedido.avro.model.PagamentoResponseAvroModel.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'sagaId' field.
      * @return The value.
      */
    public java.lang.String getSagaId() {
      return sagaId;
    }


    /**
      * Sets the value of the 'sagaId' field.
      * @param value The value of 'sagaId'.
      * @return This builder.
      */
    public org.vortxyz.kafka.pedido.avro.model.PagamentoResponseAvroModel.Builder setSagaId(java.lang.String value) {
      validate(fields()[1], value);
      this.sagaId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'sagaId' field has been set.
      * @return True if the 'sagaId' field has been set, false otherwise.
      */
    public boolean hasSagaId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'sagaId' field.
      * @return This builder.
      */
    public org.vortxyz.kafka.pedido.avro.model.PagamentoResponseAvroModel.Builder clearSagaId() {
      sagaId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'pagamentoId' field.
      * @return The value.
      */
    public java.lang.String getPagamentoId() {
      return pagamentoId;
    }


    /**
      * Sets the value of the 'pagamentoId' field.
      * @param value The value of 'pagamentoId'.
      * @return This builder.
      */
    public org.vortxyz.kafka.pedido.avro.model.PagamentoResponseAvroModel.Builder setPagamentoId(java.lang.String value) {
      validate(fields()[2], value);
      this.pagamentoId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'pagamentoId' field has been set.
      * @return True if the 'pagamentoId' field has been set, false otherwise.
      */
    public boolean hasPagamentoId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'pagamentoId' field.
      * @return This builder.
      */
    public org.vortxyz.kafka.pedido.avro.model.PagamentoResponseAvroModel.Builder clearPagamentoId() {
      pagamentoId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'clienteId' field.
      * @return The value.
      */
    public java.lang.String getClienteId() {
      return clienteId;
    }


    /**
      * Sets the value of the 'clienteId' field.
      * @param value The value of 'clienteId'.
      * @return This builder.
      */
    public org.vortxyz.kafka.pedido.avro.model.PagamentoResponseAvroModel.Builder setClienteId(java.lang.String value) {
      validate(fields()[3], value);
      this.clienteId = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'clienteId' field has been set.
      * @return True if the 'clienteId' field has been set, false otherwise.
      */
    public boolean hasClienteId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'clienteId' field.
      * @return This builder.
      */
    public org.vortxyz.kafka.pedido.avro.model.PagamentoResponseAvroModel.Builder clearClienteId() {
      clienteId = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'pedidoId' field.
      * @return The value.
      */
    public java.lang.String getPedidoId() {
      return pedidoId;
    }


    /**
      * Sets the value of the 'pedidoId' field.
      * @param value The value of 'pedidoId'.
      * @return This builder.
      */
    public org.vortxyz.kafka.pedido.avro.model.PagamentoResponseAvroModel.Builder setPedidoId(java.lang.String value) {
      validate(fields()[4], value);
      this.pedidoId = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'pedidoId' field has been set.
      * @return True if the 'pedidoId' field has been set, false otherwise.
      */
    public boolean hasPedidoId() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'pedidoId' field.
      * @return This builder.
      */
    public org.vortxyz.kafka.pedido.avro.model.PagamentoResponseAvroModel.Builder clearPedidoId() {
      pedidoId = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'preco' field.
      * @return The value.
      */
    public java.math.BigDecimal getPreco() {
      return preco;
    }


    /**
      * Sets the value of the 'preco' field.
      * @param value The value of 'preco'.
      * @return This builder.
      */
    public org.vortxyz.kafka.pedido.avro.model.PagamentoResponseAvroModel.Builder setPreco(java.math.BigDecimal value) {
      validate(fields()[5], value);
      this.preco = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'preco' field has been set.
      * @return True if the 'preco' field has been set, false otherwise.
      */
    public boolean hasPreco() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'preco' field.
      * @return This builder.
      */
    public org.vortxyz.kafka.pedido.avro.model.PagamentoResponseAvroModel.Builder clearPreco() {
      preco = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'criadoEm' field.
      * @return The value.
      */
    public java.time.Instant getCriadoEm() {
      return criadoEm;
    }


    /**
      * Sets the value of the 'criadoEm' field.
      * @param value The value of 'criadoEm'.
      * @return This builder.
      */
    public org.vortxyz.kafka.pedido.avro.model.PagamentoResponseAvroModel.Builder setCriadoEm(java.time.Instant value) {
      validate(fields()[6], value);
      this.criadoEm = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'criadoEm' field has been set.
      * @return True if the 'criadoEm' field has been set, false otherwise.
      */
    public boolean hasCriadoEm() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'criadoEm' field.
      * @return This builder.
      */
    public org.vortxyz.kafka.pedido.avro.model.PagamentoResponseAvroModel.Builder clearCriadoEm() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'pagamentoStatus' field.
      * @return The value.
      */
    public org.vortxyz.kafka.pedido.avro.model.PagamentoStatus getPagamentoStatus() {
      return pagamentoStatus;
    }


    /**
      * Sets the value of the 'pagamentoStatus' field.
      * @param value The value of 'pagamentoStatus'.
      * @return This builder.
      */
    public org.vortxyz.kafka.pedido.avro.model.PagamentoResponseAvroModel.Builder setPagamentoStatus(org.vortxyz.kafka.pedido.avro.model.PagamentoStatus value) {
      validate(fields()[7], value);
      this.pagamentoStatus = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'pagamentoStatus' field has been set.
      * @return True if the 'pagamentoStatus' field has been set, false otherwise.
      */
    public boolean hasPagamentoStatus() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'pagamentoStatus' field.
      * @return This builder.
      */
    public org.vortxyz.kafka.pedido.avro.model.PagamentoResponseAvroModel.Builder clearPagamentoStatus() {
      pagamentoStatus = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'mensagensFalha' field.
      * @return The value.
      */
    public java.util.List<java.lang.String> getMensagensFalha() {
      return mensagensFalha;
    }


    /**
      * Sets the value of the 'mensagensFalha' field.
      * @param value The value of 'mensagensFalha'.
      * @return This builder.
      */
    public org.vortxyz.kafka.pedido.avro.model.PagamentoResponseAvroModel.Builder setMensagensFalha(java.util.List<java.lang.String> value) {
      validate(fields()[8], value);
      this.mensagensFalha = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'mensagensFalha' field has been set.
      * @return True if the 'mensagensFalha' field has been set, false otherwise.
      */
    public boolean hasMensagensFalha() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'mensagensFalha' field.
      * @return This builder.
      */
    public org.vortxyz.kafka.pedido.avro.model.PagamentoResponseAvroModel.Builder clearMensagensFalha() {
      mensagensFalha = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PagamentoResponseAvroModel build() {
      try {
        PagamentoResponseAvroModel record = new PagamentoResponseAvroModel();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.String) defaultValue(fields()[0]);
        record.sagaId = fieldSetFlags()[1] ? this.sagaId : (java.lang.String) defaultValue(fields()[1]);
        record.pagamentoId = fieldSetFlags()[2] ? this.pagamentoId : (java.lang.String) defaultValue(fields()[2]);
        record.clienteId = fieldSetFlags()[3] ? this.clienteId : (java.lang.String) defaultValue(fields()[3]);
        record.pedidoId = fieldSetFlags()[4] ? this.pedidoId : (java.lang.String) defaultValue(fields()[4]);
        record.preco = fieldSetFlags()[5] ? this.preco : (java.math.BigDecimal) defaultValue(fields()[5]);
        record.criadoEm = fieldSetFlags()[6] ? this.criadoEm : (java.time.Instant) defaultValue(fields()[6]);
        record.pagamentoStatus = fieldSetFlags()[7] ? this.pagamentoStatus : (org.vortxyz.kafka.pedido.avro.model.PagamentoStatus) defaultValue(fields()[7]);
        record.mensagensFalha = fieldSetFlags()[8] ? this.mensagensFalha : (java.util.List<java.lang.String>) defaultValue(fields()[8]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<PagamentoResponseAvroModel>
    WRITER$ = (org.apache.avro.io.DatumWriter<PagamentoResponseAvroModel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<PagamentoResponseAvroModel>
    READER$ = (org.apache.avro.io.DatumReader<PagamentoResponseAvroModel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










