/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.vortxyz.kafka.pedido.avro.model;
@org.apache.avro.specific.AvroGenerated
public enum PedidoPagamentoStatus implements org.apache.avro.generic.GenericEnumSymbol<PedidoPagamentoStatus> {
  PENDENTE, CANCELADO  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"PedidoPagamentoStatus\",\"namespace\":\"org.vortxyz.kafka.pedido.avro.model\",\"symbols\":[\"PENDENTE\",\"CANCELADO\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
