/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.vortxyz.kafka.pedido.avro.model;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class PedidoAprovacaoRequestAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6804814688563621531L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PedidoAprovacaoRequestAvroModel\",\"namespace\":\"org.vortxyz.kafka.pedido.avro.model\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"sagaId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"restauranteId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"pedidoId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"restaurantePedidoStatus\",\"type\":{\"type\":\"enum\",\"name\":\"RestaurantePedidoStatus\",\"symbols\":[\"PAGO\"]}},{\"name\":\"produtos\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Produto\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"logicalType\":\"uuid\"},{\"name\":\"quantidade\",\"type\":\"int\"}]}}},{\"name\":\"preco\",\"type\":{\"type\":\"bytes\",\"logicalType\":\"decimal\",\"precision\":10,\"scale\":2}},{\"name\":\"criadoEm\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
    MODEL$.addLogicalTypeConversion(new org.apache.avro.Conversions.DecimalConversion());
  }

  private static final BinaryMessageEncoder<PedidoAprovacaoRequestAvroModel> ENCODER =
      new BinaryMessageEncoder<PedidoAprovacaoRequestAvroModel>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<PedidoAprovacaoRequestAvroModel> DECODER =
      new BinaryMessageDecoder<PedidoAprovacaoRequestAvroModel>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<PedidoAprovacaoRequestAvroModel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<PedidoAprovacaoRequestAvroModel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<PedidoAprovacaoRequestAvroModel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<PedidoAprovacaoRequestAvroModel>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this PedidoAprovacaoRequestAvroModel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a PedidoAprovacaoRequestAvroModel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a PedidoAprovacaoRequestAvroModel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static PedidoAprovacaoRequestAvroModel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String id;
  private java.lang.String sagaId;
  private java.lang.String restauranteId;
  private java.lang.String pedidoId;
  private org.vortxyz.kafka.pedido.avro.model.RestaurantePedidoStatus restaurantePedidoStatus;
  private java.util.List<org.vortxyz.kafka.pedido.avro.model.Produto> produtos;
  private java.math.BigDecimal preco;
  private java.time.Instant criadoEm;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PedidoAprovacaoRequestAvroModel() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param sagaId The new value for sagaId
   * @param restauranteId The new value for restauranteId
   * @param pedidoId The new value for pedidoId
   * @param restaurantePedidoStatus The new value for restaurantePedidoStatus
   * @param produtos The new value for produtos
   * @param preco The new value for preco
   * @param criadoEm The new value for criadoEm
   */
  public PedidoAprovacaoRequestAvroModel(java.lang.String id, java.lang.String sagaId, java.lang.String restauranteId, java.lang.String pedidoId, org.vortxyz.kafka.pedido.avro.model.RestaurantePedidoStatus restaurantePedidoStatus, java.util.List<org.vortxyz.kafka.pedido.avro.model.Produto> produtos, java.math.BigDecimal preco, java.time.Instant criadoEm) {
    this.id = id;
    this.sagaId = sagaId;
    this.restauranteId = restauranteId;
    this.pedidoId = pedidoId;
    this.restaurantePedidoStatus = restaurantePedidoStatus;
    this.produtos = produtos;
    this.preco = preco;
    this.criadoEm = criadoEm.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return sagaId;
    case 2: return restauranteId;
    case 3: return pedidoId;
    case 4: return restaurantePedidoStatus;
    case 5: return produtos;
    case 6: return preco;
    case 7: return criadoEm;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      null,
      null,
      null,
      new org.apache.avro.Conversions.DecimalConversion(),
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = value$ != null ? value$.toString() : null; break;
    case 1: sagaId = value$ != null ? value$.toString() : null; break;
    case 2: restauranteId = value$ != null ? value$.toString() : null; break;
    case 3: pedidoId = value$ != null ? value$.toString() : null; break;
    case 4: restaurantePedidoStatus = (org.vortxyz.kafka.pedido.avro.model.RestaurantePedidoStatus)value$; break;
    case 5: produtos = (java.util.List<org.vortxyz.kafka.pedido.avro.model.Produto>)value$; break;
    case 6: preco = (java.math.BigDecimal)value$; break;
    case 7: criadoEm = (java.time.Instant)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.String getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.String value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'sagaId' field.
   * @return The value of the 'sagaId' field.
   */
  public java.lang.String getSagaId() {
    return sagaId;
  }


  /**
   * Sets the value of the 'sagaId' field.
   * @param value the value to set.
   */
  public void setSagaId(java.lang.String value) {
    this.sagaId = value;
  }

  /**
   * Gets the value of the 'restauranteId' field.
   * @return The value of the 'restauranteId' field.
   */
  public java.lang.String getRestauranteId() {
    return restauranteId;
  }


  /**
   * Sets the value of the 'restauranteId' field.
   * @param value the value to set.
   */
  public void setRestauranteId(java.lang.String value) {
    this.restauranteId = value;
  }

  /**
   * Gets the value of the 'pedidoId' field.
   * @return The value of the 'pedidoId' field.
   */
  public java.lang.String getPedidoId() {
    return pedidoId;
  }


  /**
   * Sets the value of the 'pedidoId' field.
   * @param value the value to set.
   */
  public void setPedidoId(java.lang.String value) {
    this.pedidoId = value;
  }

  /**
   * Gets the value of the 'restaurantePedidoStatus' field.
   * @return The value of the 'restaurantePedidoStatus' field.
   */
  public org.vortxyz.kafka.pedido.avro.model.RestaurantePedidoStatus getRestaurantePedidoStatus() {
    return restaurantePedidoStatus;
  }


  /**
   * Sets the value of the 'restaurantePedidoStatus' field.
   * @param value the value to set.
   */
  public void setRestaurantePedidoStatus(org.vortxyz.kafka.pedido.avro.model.RestaurantePedidoStatus value) {
    this.restaurantePedidoStatus = value;
  }

  /**
   * Gets the value of the 'produtos' field.
   * @return The value of the 'produtos' field.
   */
  public java.util.List<org.vortxyz.kafka.pedido.avro.model.Produto> getProdutos() {
    return produtos;
  }


  /**
   * Sets the value of the 'produtos' field.
   * @param value the value to set.
   */
  public void setProdutos(java.util.List<org.vortxyz.kafka.pedido.avro.model.Produto> value) {
    this.produtos = value;
  }

  /**
   * Gets the value of the 'preco' field.
   * @return The value of the 'preco' field.
   */
  public java.math.BigDecimal getPreco() {
    return preco;
  }


  /**
   * Sets the value of the 'preco' field.
   * @param value the value to set.
   */
  public void setPreco(java.math.BigDecimal value) {
    this.preco = value;
  }

  /**
   * Gets the value of the 'criadoEm' field.
   * @return The value of the 'criadoEm' field.
   */
  public java.time.Instant getCriadoEm() {
    return criadoEm;
  }


  /**
   * Sets the value of the 'criadoEm' field.
   * @param value the value to set.
   */
  public void setCriadoEm(java.time.Instant value) {
    this.criadoEm = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Creates a new PedidoAprovacaoRequestAvroModel RecordBuilder.
   * @return A new PedidoAprovacaoRequestAvroModel RecordBuilder
   */
  public static org.vortxyz.kafka.pedido.avro.model.PedidoAprovacaoRequestAvroModel.Builder builder() {
    return new org.vortxyz.kafka.pedido.avro.model.PedidoAprovacaoRequestAvroModel.Builder();
  }

  /**
   * Creates a new PedidoAprovacaoRequestAvroModel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PedidoAprovacaoRequestAvroModel RecordBuilder
   */
  public static org.vortxyz.kafka.pedido.avro.model.PedidoAprovacaoRequestAvroModel.Builder builder(org.vortxyz.kafka.pedido.avro.model.PedidoAprovacaoRequestAvroModel.Builder other) {
    if (other == null) {
      return new org.vortxyz.kafka.pedido.avro.model.PedidoAprovacaoRequestAvroModel.Builder();
    } else {
      return new org.vortxyz.kafka.pedido.avro.model.PedidoAprovacaoRequestAvroModel.Builder(other);
    }
  }

  /**
   * Creates a new PedidoAprovacaoRequestAvroModel RecordBuilder by copying an existing PedidoAprovacaoRequestAvroModel instance.
   * @param other The existing instance to copy.
   * @return A new PedidoAprovacaoRequestAvroModel RecordBuilder
   */
  public static org.vortxyz.kafka.pedido.avro.model.PedidoAprovacaoRequestAvroModel.Builder builder(org.vortxyz.kafka.pedido.avro.model.PedidoAprovacaoRequestAvroModel other) {
    if (other == null) {
      return new org.vortxyz.kafka.pedido.avro.model.PedidoAprovacaoRequestAvroModel.Builder();
    } else {
      return new org.vortxyz.kafka.pedido.avro.model.PedidoAprovacaoRequestAvroModel.Builder(other);
    }
  }

  /**
   * RecordBuilder for PedidoAprovacaoRequestAvroModel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PedidoAprovacaoRequestAvroModel>
    implements org.apache.avro.data.RecordBuilder<PedidoAprovacaoRequestAvroModel> {

    private java.lang.String id;
    private java.lang.String sagaId;
    private java.lang.String restauranteId;
    private java.lang.String pedidoId;
    private org.vortxyz.kafka.pedido.avro.model.RestaurantePedidoStatus restaurantePedidoStatus;
    private java.util.List<org.vortxyz.kafka.pedido.avro.model.Produto> produtos;
    private java.math.BigDecimal preco;
    private java.time.Instant criadoEm;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.vortxyz.kafka.pedido.avro.model.PedidoAprovacaoRequestAvroModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.sagaId)) {
        this.sagaId = data().deepCopy(fields()[1].schema(), other.sagaId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.restauranteId)) {
        this.restauranteId = data().deepCopy(fields()[2].schema(), other.restauranteId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.pedidoId)) {
        this.pedidoId = data().deepCopy(fields()[3].schema(), other.pedidoId);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.restaurantePedidoStatus)) {
        this.restaurantePedidoStatus = data().deepCopy(fields()[4].schema(), other.restaurantePedidoStatus);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.produtos)) {
        this.produtos = data().deepCopy(fields()[5].schema(), other.produtos);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.preco)) {
        this.preco = data().deepCopy(fields()[6].schema(), other.preco);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.criadoEm)) {
        this.criadoEm = data().deepCopy(fields()[7].schema(), other.criadoEm);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
    }

    /**
     * Creates a Builder by copying an existing PedidoAprovacaoRequestAvroModel instance
     * @param other The existing instance to copy.
     */
    private Builder(org.vortxyz.kafka.pedido.avro.model.PedidoAprovacaoRequestAvroModel other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.sagaId)) {
        this.sagaId = data().deepCopy(fields()[1].schema(), other.sagaId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.restauranteId)) {
        this.restauranteId = data().deepCopy(fields()[2].schema(), other.restauranteId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.pedidoId)) {
        this.pedidoId = data().deepCopy(fields()[3].schema(), other.pedidoId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.restaurantePedidoStatus)) {
        this.restaurantePedidoStatus = data().deepCopy(fields()[4].schema(), other.restaurantePedidoStatus);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.produtos)) {
        this.produtos = data().deepCopy(fields()[5].schema(), other.produtos);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.preco)) {
        this.preco = data().deepCopy(fields()[6].schema(), other.preco);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.criadoEm)) {
        this.criadoEm = data().deepCopy(fields()[7].schema(), other.criadoEm);
        fieldSetFlags()[7] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.String getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public org.vortxyz.kafka.pedido.avro.model.PedidoAprovacaoRequestAvroModel.Builder setId(java.lang.String value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public org.vortxyz.kafka.pedido.avro.model.PedidoAprovacaoRequestAvroModel.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'sagaId' field.
      * @return The value.
      */
    public java.lang.String getSagaId() {
      return sagaId;
    }


    /**
      * Sets the value of the 'sagaId' field.
      * @param value The value of 'sagaId'.
      * @return This builder.
      */
    public org.vortxyz.kafka.pedido.avro.model.PedidoAprovacaoRequestAvroModel.Builder setSagaId(java.lang.String value) {
      validate(fields()[1], value);
      this.sagaId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'sagaId' field has been set.
      * @return True if the 'sagaId' field has been set, false otherwise.
      */
    public boolean hasSagaId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'sagaId' field.
      * @return This builder.
      */
    public org.vortxyz.kafka.pedido.avro.model.PedidoAprovacaoRequestAvroModel.Builder clearSagaId() {
      sagaId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'restauranteId' field.
      * @return The value.
      */
    public java.lang.String getRestauranteId() {
      return restauranteId;
    }


    /**
      * Sets the value of the 'restauranteId' field.
      * @param value The value of 'restauranteId'.
      * @return This builder.
      */
    public org.vortxyz.kafka.pedido.avro.model.PedidoAprovacaoRequestAvroModel.Builder setRestauranteId(java.lang.String value) {
      validate(fields()[2], value);
      this.restauranteId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'restauranteId' field has been set.
      * @return True if the 'restauranteId' field has been set, false otherwise.
      */
    public boolean hasRestauranteId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'restauranteId' field.
      * @return This builder.
      */
    public org.vortxyz.kafka.pedido.avro.model.PedidoAprovacaoRequestAvroModel.Builder clearRestauranteId() {
      restauranteId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'pedidoId' field.
      * @return The value.
      */
    public java.lang.String getPedidoId() {
      return pedidoId;
    }


    /**
      * Sets the value of the 'pedidoId' field.
      * @param value The value of 'pedidoId'.
      * @return This builder.
      */
    public org.vortxyz.kafka.pedido.avro.model.PedidoAprovacaoRequestAvroModel.Builder setPedidoId(java.lang.String value) {
      validate(fields()[3], value);
      this.pedidoId = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'pedidoId' field has been set.
      * @return True if the 'pedidoId' field has been set, false otherwise.
      */
    public boolean hasPedidoId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'pedidoId' field.
      * @return This builder.
      */
    public org.vortxyz.kafka.pedido.avro.model.PedidoAprovacaoRequestAvroModel.Builder clearPedidoId() {
      pedidoId = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'restaurantePedidoStatus' field.
      * @return The value.
      */
    public org.vortxyz.kafka.pedido.avro.model.RestaurantePedidoStatus getRestaurantePedidoStatus() {
      return restaurantePedidoStatus;
    }


    /**
      * Sets the value of the 'restaurantePedidoStatus' field.
      * @param value The value of 'restaurantePedidoStatus'.
      * @return This builder.
      */
    public org.vortxyz.kafka.pedido.avro.model.PedidoAprovacaoRequestAvroModel.Builder setRestaurantePedidoStatus(org.vortxyz.kafka.pedido.avro.model.RestaurantePedidoStatus value) {
      validate(fields()[4], value);
      this.restaurantePedidoStatus = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'restaurantePedidoStatus' field has been set.
      * @return True if the 'restaurantePedidoStatus' field has been set, false otherwise.
      */
    public boolean hasRestaurantePedidoStatus() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'restaurantePedidoStatus' field.
      * @return This builder.
      */
    public org.vortxyz.kafka.pedido.avro.model.PedidoAprovacaoRequestAvroModel.Builder clearRestaurantePedidoStatus() {
      restaurantePedidoStatus = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'produtos' field.
      * @return The value.
      */
    public java.util.List<org.vortxyz.kafka.pedido.avro.model.Produto> getProdutos() {
      return produtos;
    }


    /**
      * Sets the value of the 'produtos' field.
      * @param value The value of 'produtos'.
      * @return This builder.
      */
    public org.vortxyz.kafka.pedido.avro.model.PedidoAprovacaoRequestAvroModel.Builder setProdutos(java.util.List<org.vortxyz.kafka.pedido.avro.model.Produto> value) {
      validate(fields()[5], value);
      this.produtos = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'produtos' field has been set.
      * @return True if the 'produtos' field has been set, false otherwise.
      */
    public boolean hasProdutos() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'produtos' field.
      * @return This builder.
      */
    public org.vortxyz.kafka.pedido.avro.model.PedidoAprovacaoRequestAvroModel.Builder clearProdutos() {
      produtos = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'preco' field.
      * @return The value.
      */
    public java.math.BigDecimal getPreco() {
      return preco;
    }


    /**
      * Sets the value of the 'preco' field.
      * @param value The value of 'preco'.
      * @return This builder.
      */
    public org.vortxyz.kafka.pedido.avro.model.PedidoAprovacaoRequestAvroModel.Builder setPreco(java.math.BigDecimal value) {
      validate(fields()[6], value);
      this.preco = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'preco' field has been set.
      * @return True if the 'preco' field has been set, false otherwise.
      */
    public boolean hasPreco() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'preco' field.
      * @return This builder.
      */
    public org.vortxyz.kafka.pedido.avro.model.PedidoAprovacaoRequestAvroModel.Builder clearPreco() {
      preco = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'criadoEm' field.
      * @return The value.
      */
    public java.time.Instant getCriadoEm() {
      return criadoEm;
    }


    /**
      * Sets the value of the 'criadoEm' field.
      * @param value The value of 'criadoEm'.
      * @return This builder.
      */
    public org.vortxyz.kafka.pedido.avro.model.PedidoAprovacaoRequestAvroModel.Builder setCriadoEm(java.time.Instant value) {
      validate(fields()[7], value);
      this.criadoEm = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'criadoEm' field has been set.
      * @return True if the 'criadoEm' field has been set, false otherwise.
      */
    public boolean hasCriadoEm() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'criadoEm' field.
      * @return This builder.
      */
    public org.vortxyz.kafka.pedido.avro.model.PedidoAprovacaoRequestAvroModel.Builder clearCriadoEm() {
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PedidoAprovacaoRequestAvroModel build() {
      try {
        PedidoAprovacaoRequestAvroModel record = new PedidoAprovacaoRequestAvroModel();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.String) defaultValue(fields()[0]);
        record.sagaId = fieldSetFlags()[1] ? this.sagaId : (java.lang.String) defaultValue(fields()[1]);
        record.restauranteId = fieldSetFlags()[2] ? this.restauranteId : (java.lang.String) defaultValue(fields()[2]);
        record.pedidoId = fieldSetFlags()[3] ? this.pedidoId : (java.lang.String) defaultValue(fields()[3]);
        record.restaurantePedidoStatus = fieldSetFlags()[4] ? this.restaurantePedidoStatus : (org.vortxyz.kafka.pedido.avro.model.RestaurantePedidoStatus) defaultValue(fields()[4]);
        record.produtos = fieldSetFlags()[5] ? this.produtos : (java.util.List<org.vortxyz.kafka.pedido.avro.model.Produto>) defaultValue(fields()[5]);
        record.preco = fieldSetFlags()[6] ? this.preco : (java.math.BigDecimal) defaultValue(fields()[6]);
        record.criadoEm = fieldSetFlags()[7] ? this.criadoEm : (java.time.Instant) defaultValue(fields()[7]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<PedidoAprovacaoRequestAvroModel>
    WRITER$ = (org.apache.avro.io.DatumWriter<PedidoAprovacaoRequestAvroModel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<PedidoAprovacaoRequestAvroModel>
    READER$ = (org.apache.avro.io.DatumReader<PedidoAprovacaoRequestAvroModel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










