/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.vortxyz.kafka.pedido.avro.model;
@org.apache.avro.specific.AvroGenerated
public enum PedidoAprovacaoStatus implements org.apache.avro.generic.GenericEnumSymbol<PedidoAprovacaoStatus> {
  APROVADO, REJEITADO  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"PedidoAprovacaoStatus\",\"namespace\":\"org.vortxyz.kafka.pedido.avro.model\",\"symbols\":[\"APROVADO\",\"REJEITADO\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
