/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.vortxyz.kafka.pedido.avro.model;
@org.apache.avro.specific.AvroGenerated
public enum RestaurantePedidoStatus implements org.apache.avro.generic.GenericEnumSymbol<RestaurantePedidoStatus> {
  PAGO  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"RestaurantePedidoStatus\",\"namespace\":\"org.vortxyz.kafka.pedido.avro.model\",\"symbols\":[\"PAGO\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
